**_Copyright Notice_**

This notebook is available for educational purposes. You may not use or distribute this notebook for commercial purposes. You may make copies of this notebook and use or distribute it for educational purposes as long as you cite the author as the source of the notebook.

Jaeyoung Chun | School of Applied Artificial Intelligence | Handong Global University

# EDA on International Match Data

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.2'

## Load International Match Data

In [3]:
match = pd.read_csv('../data/results.csv')

In [4]:
match

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
49440,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49441,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49442,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49443,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49444,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

## Tournament Types

In [5]:
match.tournament.unique()

array(['Friendly', 'British Home Championship', 'Évence Coppée Trophy',
       'Muratti Vase', 'Copa Lipton', 'Copa Newton',
       'Copa Premio Honor Argentino', 'Olympic Games',
       'Copa Premio Honor Uruguayo', 'Far Eastern Championship Games',
       'Copa Roca', 'Copa América', 'Inter-Allied Games', 'Peace Cup',
       'Open International Championship', 'Soccer Ashes',
       'Copa Chevallier Boutell', 'Nordic Championship',
       'Central European International Cup', 'Baltic Cup', 'Balkan Cup',
       'Central American and Caribbean Games', 'FIFA World Cup',
       'Copa Rio Branco', 'FIFA World Cup qualification',
       'Bolivarian Games', 'CCCF Championship', 'NAFC Championship',
       'Copa Oswaldo Cruz', 'Asian Games', 'Pan American Championship',
       'Copa del Pacífico', "Copa Bernardo O'Higgins",
       'AFC Asian Cup qualification', 'Atlantic Cup', 'AFC Asian Cup',
       'African Cup of Nations', 'Copa Paz del Chaco',
       'Merdeka Tournament', 'UEFA Euro qualification',
       'Southeast Asian Peninsular Games', 'African Friendship Games',
       'UEFA Euro', 'Windward Islands Tournament',
       'African Cup of Nations qualification', 'Vietnam Independence Cup',
       'Copa Carlos Dittborn', 'Phillip Seaga Cup',
       'CONCACAF Championship', 'Copa Juan Pinto Durán', 'Arab Cup',
       'South Pacific Games', 'Zambian Independence Tournament',
       'CONCACAF Championship qualification', 'Copa Artigas',
       'All-African Games', 'GaNEFo', 'Copa América qualification',
       "King's Cup", 'Gulf Cup', 'Indonesia Tournament', 'Korea Cup',
       'Palestine Cup', 'Brazil Independence Cup', 'Copa Ramón Castilla',
       'Oceania Nations Cup', 'CECAFA Cup', 'Kuneitra Cup',
       'Copa Félix Bogado', 'Real Madrid 75th Anniversary Cup',
       'Beijing International Friendship Tournament',
       'Southeast Asian Games', 'Kirin Cup',
       'CFU Caribbean Cup qualification', 'CFU Caribbean Cup',
       'Amílcar Cabral Cup', 'FIFA 75th Anniversary Cup',
       'Indian Ocean Island Games',
       'Guangzhou International Friendship Tournament', 'Mundialito',
       'South Pacific Mini Games', 'West African Cup', 'Nehru Cup',
       'Merlion Cup', 'Trans-Tasman Cup', 'Great Wall Cup',
       'South Asian Games', 'UDEAC Cup', 'Rous Cup',
       'CONMEBOL–UEFA Cup of Champions', 'Miami Cup',
       'Lunar New Year Cup', 'Arab Cup qualification',
       'Tournoi de France', 'Malta International Tournament',
       'Four Nations Tournament', 'Matthews Cup',
       'Tournament Burkina Faso', 'Marlboro Cup', 'Melanesia Cup',
       'Island Games', 'NAFU Championship', 'Dynasty Cup',
       'Dakar Tournament', 'UNCAF Cup', 'Scania 100 Tournament',
       'Gold Cup', 'USA Cup', 'Jordan International Tournament',
       'Confederations Cup', 'East Asian Games',
       'United Arab Emirates Friendship Tournament', 'Joe Robbie Cup',
       'Oceania Nations Cup qualification', 'Simba Tournament',
       'SAFF Cup', 'AFF Championship', 'King Hassan II Tournament',
       'Cyprus International Tournament', 'Dunhill Cup',
       'COSAFA Cup qualification', 'COSAFA Cup', 'Gold Cup qualification',
       'AFF Championship qualification', 'SKN Football Festival',
       "Four Nations' Cup", 'UNIFFAC Cup', 'WAFF Championship',
       'Millennium Cup', 'Cup of Ancient Civilizations',
       "Prime Minister's Cup", 'Unity Cup', 'The Other Final',
       'EAFF Championship', 'TIFOCO Tournament', 'Afro-Asian Games',
       'AFC Challenge Cup', 'FIFI Wild Cup', 'ELF Cup', 'Viva World Cup',
       'AFC Challenge Cup qualification', "Coupe de l'Outre-Mer",
       'VFF Cup', 'Corsica Cup', 'Dragon Cup', 'ABCS Tournament',
       'Nile Basin Tournament', 'Nations Cup', 'Copa Confraternidad',
       'Pacific Games', 'Superclásico de las Américas',
       'Palestine International Championship', 'Philippine Peace Cup',
       'Kirin Challenge Cup',
       'International Tournament of Peoples, Cultures and Tribes',
       'Tynwald Hill Tournament', 'OSN Cup', 'CONIFA World Football Cup',
       'Niamh Challenge Cup', 'CONIFA European Football Cup',
       'Benedikt Fontana Cup', 'ConIFA Challenger Cup',
       'Hungary Heritage Cup', 'World Unity Cup', 'AFC Solidarity Cup',
       'Pacific Mini Games', 'Intercontinental Cup',
       'UEFA Nations League', 'CONCACAF Nations League qualification',
       'Atlantic Heritage Cup', 'Inter Games', 'CONCACAF Nations League',
       'CONIFA World Cup qualification', 'Three Nations Cup',
       'Mahinda Rajapaksa Cup', 'Navruz Cup',
       'CONIFA Africa Football Cup', 'CONIFA South America Football Cup',
       "MSG Prime Minister's Cup", 'Tri Nation Tournament',
       'CAFA Nations Cup', 'Mauritius Four Nations Cup',
       'CONIFA World Football Cup qualification', 'CONIFA Asia Cup',
       'FIFA Series', 'Marianas Cup', 'Tri-Nations Series',
       'ASEAN Championship qualification', 'ASEAN Championship',
       'EAFF Championship qualification', 'Mapinduzi Cup',
       'Canadian Shield', 'Outrigger Challenge Cup',
       'South Asian Super Cup', 'CONCACAF Series',
       'Al Ain International Cup', 'Morocco, Capital of African Football',
       'Mukuru 4 Nations',
       'Diamond Jubilee International Football Tournament',
       'Tri-Nations Cup'], dtype=object)

## Convert to DateTime

In [6]:
match["date"] = pd.to_datetime(match["date"])

In [7]:
match.dtypes

date          datetime64[ns]
home_team             object
away_team             object
home_score           float64
away_score           float64
tournament            object
city                  object
country               object
neutral                 bool
dtype: object

## Keep Only 2022

In [8]:
match_2022 = match[ match["date"].dt.year == 2022 ].copy()

In [9]:
match_2022

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
44837,2022-01-01,Thailand,Indonesia,2.0,2.0,AFF Championship,Kallang,Singapore,True
44838,2022-01-02,Gabon,Burkina Faso,0.0,3.0,Friendly,Dubai,United Arab Emirates,True
44839,2022-01-02,Sudan,Zimbabwe,0.0,0.0,Friendly,Yaoundé,Cameroon,True
44840,2022-01-03,Rwanda,Guinea,3.0,0.0,Friendly,Kigali,Rwanda,False
44841,2022-01-04,Mauritania,Gabon,1.0,1.0,Friendly,Dubai,United Arab Emirates,True
...,...,...,...,...,...,...,...,...,...
45801,2022-12-30,Iraq,Kuwait,1.0,0.0,Friendly,Basra,Iraq,False
45802,2022-12-30,Oman,Syria,1.0,0.0,Friendly,Dubai,United Arab Emirates,True
45803,2022-12-30,United Arab Emirates,Lebanon,1.0,0.0,Friendly,Abu Dhabi,United Arab Emirates,False
45804,2022-12-30,Myanmar,Laos,2.0,2.0,AFF Championship,Yangon,Myanmar,False
45805,2022-12-30,Singapore,Vietnam,0.0,0.0,AFF Championship,Singapore,Singapore,False

## Keep Only South Korea

In [10]:
match_2022_kor = match_2022[ match_2022.home_team == "South Korea" ].copy()

In [11]:
match_2022_kor

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
44863,2022-01-15,South Korea,Iceland,5.0,1.0,Friendly,Antalya,Turkey,True
44881,2022-01-20,South Korea,Moldova,4.0,0.0,Friendly,Antalya,Turkey,True
44978,2022-03-24,South Korea,Iran,2.0,0.0,FIFA World Cup qualification,Seoul,South Korea,False
45185,2022-06-02,South Korea,Brazil,1.0,5.0,Friendly,Seoul,South Korea,False
45266,2022-06-06,South Korea,Chile,2.0,0.0,Friendly,Daejeon,South Korea,False
45344,2022-06-10,South Korea,Paraguay,2.0,2.0,Friendly,Suwon,South Korea,False
45439,2022-06-14,South Korea,Egypt,4.0,1.0,Friendly,Seoul,South Korea,False
45469,2022-07-24,South Korea,Hong Kong,3.0,0.0,EAFF Championship,Toyota,Japan,True
45512,2022-09-23,South Korea,Costa Rica,2.0,2.0,Friendly,Goyang,South Korea,False
45592,2022-09-27,South Korea,Cameroon,1.0,0.0,Friendly,Seoul,South Korea,False
45633,2022-11-11,South Korea,Iceland,1.0,0.0,Friendly,Hwaseong,South Korea,False
45746,2022-11-28,South Korea,Ghana,2.0,3.0,FIFA World Cup,Al Rayyan,Qatar,True
45763,2022-12-02,South Korea,Portugal,2.0,1.0,FIFA World Cup,Al Rayyan,Qatar,True

What is South Korea's FIFA ranking on 2022-09-27 (the date when the match with Cameroon was held)?