**_Copyright Notice_**

This notebook is available for educational purposes. You may not use or distribute this notebook for commercial purposes. You may make copies of this notebook and use or distribute it for educational purposes as long as you cite the author as the source of the notebook.

Jaeyoung Chun | School of Applied Artificial Intelligence | Handong Global University

# Prep FIFA Ranking Data

In [1]:
import pandas as pd
import os

In [2]:
pd.__version__

'2.3.2'

## Load FIFA Ranking Data

`fifa_ranking-2022-10-06.csv` contains FIFA ranking data from 1992-12-31 to 2022-10-06.

In [3]:
rank = pd.read_csv('../data/fifa_ranking-2022-10-06.csv')

In [4]:
rank

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
0,1,Germany,GER,57.00,0.00,0,UEFA,1992-12-31
1,96,Syria,SYR,11.00,0.00,0,AFC,1992-12-31
2,97,Burkina Faso,BFA,11.00,0.00,0,CAF,1992-12-31
3,99,Latvia,LVA,10.00,0.00,0,UEFA,1992-12-31
4,100,Burundi,BDI,10.00,0.00,0,CAF,1992-12-31
...,...,...,...,...,...,...,...,...
63911,74,El Salvador,SLV,1330.51,1333.48,3,CONCACAF,2022-10-06
63912,75,Oman,OMA,1320.29,1323.03,0,AFC,2022-10-06
63913,76,Israel,ISR,1316.55,1316.35,0,UEFA,2022-10-06
63914,78,Georgia,GEO,1307.34,1296.46,-4,UEFA,2022-10-06
63915,211,San Marino,SMR,762.22,763.82,0,UEFA,2022-10-06

## Convert to DateTime

In [5]:
rank['rank_date'] = pd.to_datetime(rank['rank_date'])

## Keep Only South Korea

In [6]:
rank[ rank.country_full == "Korea Republic" ]

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
142,49,Korea Republic,KOR,28.00,0.00,0,AFC,1992-12-31
259,36,Korea Republic,KOR,40.00,28.00,-13,AFC,1993-08-08
392,36,Korea Republic,KOR,39.00,40.00,0,AFC,1993-09-23
475,37,Korea Republic,KOR,39.00,39.00,1,AFC,1993-10-22
723,39,Korea Republic,KOR,38.00,39.00,2,AFC,1993-11-19
...,...,...,...,...,...,...,...,...
62961,29,Korea Republic,KOR,1522.85,1507.24,-4,AFC,2022-02-10
63202,29,Korea Republic,KOR,1519.54,1522.85,0,AFC,2022-03-31
63361,28,Korea Republic,KOR,1526.20,1519.54,-1,AFC,2022-06-23
63625,28,Korea Republic,KOR,1526.02,1526.20,0,AFC,2022-08-25
63811,28,Korea Republic,KOR,1530.30,1526.02,0,AFC,2022-10-06

In [7]:
rank_kor = rank[ rank.country_full == "Korea Republic" ].copy()

In [8]:
rank_kor

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
142,49,Korea Republic,KOR,28.00,0.00,0,AFC,1992-12-31
259,36,Korea Republic,KOR,40.00,28.00,-13,AFC,1993-08-08
392,36,Korea Republic,KOR,39.00,40.00,0,AFC,1993-09-23
475,37,Korea Republic,KOR,39.00,39.00,1,AFC,1993-10-22
723,39,Korea Republic,KOR,38.00,39.00,2,AFC,1993-11-19
...,...,...,...,...,...,...,...,...
62961,29,Korea Republic,KOR,1522.85,1507.24,-4,AFC,2022-02-10
63202,29,Korea Republic,KOR,1519.54,1522.85,0,AFC,2022-03-31
63361,28,Korea Republic,KOR,1526.20,1519.54,-1,AFC,2022-06-23
63625,28,Korea Republic,KOR,1526.02,1526.20,0,AFC,2022-08-25
63811,28,Korea Republic,KOR,1530.30,1526.02,0,AFC,2022-10-06

## Keep Rank Date >= 2018-08-01

In [9]:
rank_kor = rank_kor[ rank_kor.rank_date >= '2018-08-01'].reset_index(drop=True)

In [10]:
rank_kor

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
0,57,Korea Republic,KOR,1387.00,1388.00,0,AFC,2018-08-16
1,55,Korea Republic,KOR,1395.00,1387.00,-2,AFC,2018-09-20
2,53,Korea Republic,KOR,1401.00,1395.00,-2,AFC,2018-10-25
3,53,Korea Republic,KOR,1405.00,1401.00,0,AFC,2018-11-29
4,53,Korea Republic,KOR,1405.00,1405.00,0,AFC,2018-12-20
5,38,Korea Republic,KOR,1451.00,1405.00,-15,AFC,2019-02-07
6,37,Korea Republic,KOR,1462.00,1451.00,-1,AFC,2019-04-04
7,37,Korea Republic,KOR,1467.00,1462.00,0,AFC,2019-06-14
8,37,Korea Republic,KOR,1467.00,1467.00,0,AFC,2019-07-25
9,37,Korea Republic,KOR,1470.00,1467.00,0,AFC,2019-09-19
10,39,Korea Republic,KOR,1466.00,1470.00,2,AFC,2019-10-24
11,41,Korea Republic,KOR,1459.00,1466.00,2,AFC,2019-11-28
12,40,Korea Republic,KOR,1461.00,1459.00,-1,AFC,2019-12-19
13,40,Korea Republic,KOR,1464.00,1461.00,0,AFC,2020-02-20
14,40,Korea Republic,KOR,1464.00,1464.00,0,AFC,2020-04-09
15,40,Korea Republic,KOR,1464.00,1464.00,0,AFC,2020-06-11
16,40,Korea Republic,KOR,1464.00,1464.00,0,AFC,2020-07-16
17,39,Korea Republic,KOR,1464.00,1464.00,-1,AFC,2020-09-17
18,38,Korea Republic,KOR,1464.00,1464.00,-1,AFC,2020-10-22
19,38,Korea Republic,KOR,1465.00,1464.00,0,AFC,2020-11-26
20,38,Korea Republic,KOR,1465.00,1465.00,0,AFC,2020-12-10
21,38,Korea Republic,KOR,1465.00,1465.00,0,AFC,2021-02-18
22,39,Korea Republic,KOR,1460.25,1465.00,1,AFC,2021-04-07
23,39,Korea Republic,KOR,1460.25,1460.25,0,AFC,2021-05-27
24,36,Korea Republic,KOR,1474.96,1460.25,-3,AFC,2021-08-12
25,36,Korea Republic,KOR,1479.41,1474.96,0,AFC,2021-09-16
26,35,Korea Republic,KOR,1489.10,1479.41,-1,AFC,2021-10-21
27,33,Korea Republic,KOR,1507.24,1489.10,-2,AFC,2021-11-19
28,33,Korea Republic,KOR,1507.24,1507.24,0,AFC,2021-12-23
29,29,Korea Republic,KOR,1522.85,1507.24,-4,AFC,2022-02-10
30,29,Korea Republic,KOR,1519.54,1522.85,0,AFC,2022-03-31
31,28,Korea Republic,KOR,1526.20,1519.54,-1,AFC,2022-06-23
32,28,Korea Republic,KOR,1526.02,1526.20,0,AFC,2022-08-25
33,28,Korea Republic,KOR,1530.30,1526.02,0,AFC,2022-10-06

## Check Ranking

In [11]:
rank_kor[ rank_kor.rank_date == "2021-12-23" ]

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
28,33,Korea Republic,KOR,1507.24,1507.24,0,AFC,2021-12-23

In [12]:
rank_kor[ rank_kor.rank_date == "2021-12-24" ]

Empty DataFrame
Columns: [rank, country_full, country_abrv, total_points, previous_points, rank_change, confederation, rank_date]
Index: []

In [13]:
rank_kor[ rank_kor.rank_date == "2022-02-10" ]

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
29,29,Korea Republic,KOR,1522.85,1507.24,-4,AFC,2022-02-10

## FIFA Ranking for Everyday

- 만약에 2021-12-24에 어떤 팀과 경기가 있었다면, 그 때 한국 피파 랭킹은?
- 우리에게 주어진 데이터는 모든 날짜별로 FIFA Ranking을 가지고 있지 않음

References:

- https://pandas.pydata.org/pandas-docs/version/2.3/reference/api/pandas.DataFrame.set_index.html
- https://pandas.pydata.org/pandas-docs/version/2.3/reference/api/pandas.DataFrame.resample.html
- https://pandas.pydata.org/pandas-docs/version/2.3/reference/api/pandas.core.groupby.DataFrameGroupBy.first.html
- https://pandas.pydata.org/pandas-docs/version/2.3/reference/api/pandas.DataFrame.ffill.html
- https://pandas.pydata.org/pandas-docs/version/2.3/reference/api/pandas.DataFrame.reset_index.html

In [14]:
rank_kor.set_index("rank_date").resample("D").first()

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation
rank_date,,,,,,,
2018-08-16,57.0,Korea Republic,KOR,1387.0,1388.00,0.0,AFC
2018-08-17,NaN,None,None,NaN,NaN,NaN,None
2018-08-18,NaN,None,None,NaN,NaN,NaN,None
2018-08-19,NaN,None,None,NaN,NaN,NaN,None
2018-08-20,NaN,None,None,NaN,NaN,NaN,None
...,...,...,...,...,...,...,...
2022-10-02,NaN,None,None,NaN,NaN,NaN,None
2022-10-03,NaN,None,None,NaN,NaN,NaN,None
2022-10-04,NaN,None,None,NaN,NaN,NaN,None
2022-10-05,NaN,None,None,NaN,NaN,NaN,None
2022-10-06,28.0,Korea Republic,KOR,1530.3,1526.02,0.0,AFC

In [15]:
rank_kor.set_index("rank_date").resample("D").first().ffill()

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation
rank_date,,,,,,,
2018-08-16,57.0,Korea Republic,KOR,1387.00,1388.00,0.0,AFC
2018-08-17,57.0,Korea Republic,KOR,1387.00,1388.00,0.0,AFC
2018-08-18,57.0,Korea Republic,KOR,1387.00,1388.00,0.0,AFC
2018-08-19,57.0,Korea Republic,KOR,1387.00,1388.00,0.0,AFC
2018-08-20,57.0,Korea Republic,KOR,1387.00,1388.00,0.0,AFC
...,...,...,...,...,...,...,...
2022-10-02,28.0,Korea Republic,KOR,1526.02,1526.20,0.0,AFC
2022-10-03,28.0,Korea Republic,KOR,1526.02,1526.20,0.0,AFC
2022-10-04,28.0,Korea Republic,KOR,1526.02,1526.20,0.0,AFC
2022-10-05,28.0,Korea Republic,KOR,1526.02,1526.20,0.0,AFC
2022-10-06,28.0,Korea Republic,KOR,1530.30,1526.02,0.0,AFC

In [16]:
rank_kor.set_index("rank_date").resample("D").first().ffill().reset_index()

,rank_date,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation
0,2018-08-16,57.0,Korea Republic,KOR,1387.00,1388.00,0.0,AFC
1,2018-08-17,57.0,Korea Republic,KOR,1387.00,1388.00,0.0,AFC
2,2018-08-18,57.0,Korea Republic,KOR,1387.00,1388.00,0.0,AFC
3,2018-08-19,57.0,Korea Republic,KOR,1387.00,1388.00,0.0,AFC
4,2018-08-20,57.0,Korea Republic,KOR,1387.00,1388.00,0.0,AFC
...,...,...,...,...,...,...,...,...
1508,2022-10-02,28.0,Korea Republic,KOR,1526.02,1526.20,0.0,AFC
1509,2022-10-03,28.0,Korea Republic,KOR,1526.02,1526.20,0.0,AFC
1510,2022-10-04,28.0,Korea Republic,KOR,1526.02,1526.20,0.0,AFC
1511,2022-10-05,28.0,Korea Republic,KOR,1526.02,1526.20,0.0,AFC
1512,2022-10-06,28.0,Korea Republic,KOR,1530.30,1526.02,0.0,AFC

In [17]:
rank_kor2 = rank_kor.set_index("rank_date").resample("D").first().ffill().reset_index().copy()

In [18]:
rank_kor2.dtypes

rank_date          datetime64[ns]
rank                      float64
country_full               object
country_abrv               object
total_points              float64
previous_points           float64
rank_change               float64
confederation              object
dtype: object

In [19]:
rank_kor2 = rank_kor2.astype(
    {
        "rank": int,
        "rank_change": int
    }
)

## Check Ranking

In [20]:
rank_kor2[ rank_kor2.rank_date == "2021-12-23" ]

,rank_date,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation
1225,2021-12-23,33,Korea Republic,KOR,1507.24,1507.24,0,AFC

In [21]:
rank_kor2[ rank_kor2.rank_date == "2021-12-24" ]

,rank_date,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation
1226,2021-12-24,33,Korea Republic,KOR,1507.24,1507.24,0,AFC

In [22]:
rank_kor2[ rank_kor2.rank_date == "2022-02-10" ]

,rank_date,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation
1274,2022-02-10,29,Korea Republic,KOR,1522.85,1507.24,-4,AFC